// This file is auto-generated by Supabase
// When you update your database schema, run `npx supabase gen types typescript`
// to update this file with the latest schema types.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'user' | 'admin';

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          role: UserRole;
          created_at: string;
          updated_at: string;
          last_sign_in_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          role?: UserRole;
          created_at?: string;
          updated_at?: string;
          last_sign_in_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          role?: UserRole;
          created_at?: string;
          updated_at?: string;
          last_sign_in_at?: string | null;
        };
      };
      
      profiles: {
        Row: {
          id: string;
          user_id: string;
          first_name: string | null;
          last_name: string | null;
          avatar_url: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          first_name?: string | null;
          last_name?: string | null;
          avatar_url?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          first_name?: string | null;
          last_name?: string | null;
          avatar_url?: string | null;
          updated_at?: string;
        };
      };
      
      // Add other tables as needed
    };
    
    Views: {
      // Define your database views here
    };
    
    Functions: {
      // Define your database functions here
      handle_new_user: {
        Args: { user_id: string; email: string };
        Returns: void;
      };
    };
    
    Enums: {
      // Define your enums here
    };
    
    CompositeTypes: {
      // Define your composite types here
    };
  };
}
